# Generated by Django 2.0.1 on 2018-09-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180909_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
